homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 14.75
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_private_path
  base_url: !secret base_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret 
    aliases:
      473e1de1370cab7f01f4f2be1411cf34: 'Google Home'

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

google_assistant:
  project_id: !secret google_project_id 
  client_id: !secret google_client_id
  access_token: !secret google_access_token
  agent_user_id: !secret google_user_id
  api_key: !secret google_api_key
  expose_by_default: false
  entity_config:
    input_boolean.eagles_touchdown_mode:
      expose: true

# Text to speech
tts:
  platform: google

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

#camera:
#  - platform: rpi_camera
#    name: RaspberryPiCam
#    file_path: /home/pi/Desktop/capture/HomeAssistant.png

device_tracker:
  - platform: linksys_smart
    track_new_devices: False
    hide_if_away: False
    host: 10.0.0.1
    password: !secret router_password

notify:
  - platform: pushbullet
    name: JordanNotifications
    api_key: !secret pushbullet

wemo:

hue:
  bridges:
    - host: 10.0.0.3

# Eagles Lights Group
light:
  - platform: group
    name: Eagles Lights
    entities:
      - light.kitchen
      - light.accent_lights
      - light.bedroom

mqtt:
  broker: 127.0.0.1

script: !include scripts.yaml
automation: !include automation.yaml
input_boolean: !include input_booleans.yaml
group: !include groups.yaml








